### ISSUE TITLE
Docs To-Do

### ISSUE THREAD

**Issue by rsokl** [mit-ll-responsible-ai/hydra-zen#69]
- [x] Include links to [hydra-zen-examples](https://github.com/mit-ll-responsible-ai/hydra-zen-examples) in README and in docs
- [ ] Add some more details in README for hydra-zen-examples
- [x] Add Python 3.6 [Classifier](https://github.com/mit-ll-responsible-ai/hydra-zen/blob/9d6b842d71e9deeee385949bb002234636cd16ca/setup.py#L13)
- [x] Add [long description](https://github.com/mit-ll-responsible-ai/hydra-zen/blob/9d6b842d71e9deeee385949bb002234636cd16ca/setup.py#L34-L36)
- [x] Add changelog file

**Comment by rsokl** [comment]
We have a lot more to-do than just these things...
